[build]
  command = "npm install && npm run build:client"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  framework = "#custom"
  targetPort = 3000
  port = 3000
  command = "npm run dev"
  status = 200
